-   name: add repository ha
    copy:
        content: |
            [network_ha-clustering_Stable]
            name=Stable High Availability/Clustering packages (RedHat_RHEL-7)
            type=rpm-md
            baseurl=http://download.opensuse.org/repositories/network:/ha-clustering:/Stable/RedHat_RHEL-7/
            gpgcheck=1
            gpgkey=http://download.opensuse.org/repositories/network:/ha-clustering:/Stable/RedHat_RHEL-7//repodata/repomd.xml.key
            enabled=0
            proxy=http://proxolo.cs.poste.it:8080
        dest: /etc/yum.repos.d/network:ha-clustering:Stable.repo
-   name: add repository centos
    copy:
        content: |
            [centos-7-base]
            name=CentOS-$releasever - Base
            #mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os
            baseurl=http://mirror.centos.org/centos/7/os/$basearch/
            proxy=http://proxolo.cs.poste.it:8080
            gpgcheck=1
            gpgkey=http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7
            enabled=0
        dest: /etc/yum.repos.d/centos.repo
-   name: install packages
    yum:
        name: pacemaker,fence-agents-all,corosync,crmsh,python-pip
        state: installed
        enablerepo: centos-7-base,network_ha-clustering_Stable
    register: out_pmcs_install_packages

-   name: install python module crmsh
    pip:
        name: crmsh
        state: present
